"""drop client contact person, company, tax id

Revision ID: 13c07b8074e1
Revises: 7d374ce49eb5
Create Date: 2026-08-07 23:10:07.299867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c07b8074e1'
down_revision: Union[str, Sequence[str], None] = '7d374ce49eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('company')
        batch_op.drop_column('tax_id')
        batch_op.drop_column('contact_person')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_person', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('tax_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
